"""add model KnowledgeEntry

Revision ID: b77a8d710827
Revises: 
Create Date: 2021-05-08 13:22:46.917057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77a8d710827'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=254), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entry_title'), 'knowledge_entry', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_entry_title'), table_name='knowledge_entry')
    op.drop_table('knowledge_entry')
    # ### end Alembic commands ###
